name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  ruby-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5.x", "2.6.x"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Download MSpec
      run: |
        git clone https://github.com/ruby/mspec.git mspec
    - name: Run MSpec
      run: |
        mspec/bin/mspec
